"""empty message

Revision ID: f9c7fc931451
Revises: 522eed97fd05
Create Date: 2023-02-14 23:46:24.058947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c7fc931451'
down_revision = '522eed97fd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('dob_age',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('dob_age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
