"""empty message

Revision ID: febfd5d5f6ba
Revises: 03bdad89b615
Create Date: 2023-02-16 12:45:50.682870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'febfd5d5f6ba'
down_revision = '03bdad89b615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True)
        batch_op.alter_column('created_at_product',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status_shooping',
               existing_type=postgresql.ENUM('active', 'inactive', 'reserved', name='status_shooping_enum_2'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.alter_column('status_shooping',
               existing_type=postgresql.ENUM('active', 'inactive', 'reserved', name='status_shooping_enum_2'),
               nullable=False)
        batch_op.alter_column('created_at_product',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
